CREATE OR REPLACE TRIGGER startDGServices after startup on database
DECLARE
  db_role VARCHAR(30);
  db_open_mode VARCHAR(30);
BEGIN
  SELECT DATABASE_ROLE, OPEN_MODE INTO db_role, db_open_mode FROM V$DATABASE;
  IF db_role = 'PRIMARY' THEN 
     DBMS_SERVICE.START_SERVICE('KIS05_HA_OCI'); 
     DBMS_SERVICE.START_SERVICE('KIS05_HA_JDBC'); 
  ELSIF db_role = 'PHYSICAL STANDBY' AND db_open_mode LIKE 'READ ONLY%' THEN 
     DBMS_SERVICE.START_SERVICE('KIS05_HA_RTQ');
  ELSIF db_role = 'LOGICAL STANDBY' THEN DBMS_SERVICE.START_SERVICE('DG_LSD');
  ELSIF db_role = 'SNAPSHOT STANDBY' THEN DBMS_SERVICE.START_SERVICE('DG_RAT');
  END IF;
END;
/ 

